### ISSUE TITLE
[ConfigurationController] code http dans la réponse

### ISSUE THREAD

**Issue by lunika** [Soldras/TheliaGoogleMap#3]
La gestion des erreurs dans la réponse est géré par un paramètre error : 

```
$resp = array(
"error" => 0,
"message" => ""
);
```

il est possible de savoir si il y a une erreur en utilisant les codes http prévus à cet effet : 

* 2xx => succès
* 4xx et 5xx => erreur

Le statut se met directement dans l'objet response.

```
// ic succès, sinon mettre 500
return JsonResponse::create($data, 200);
```

Il est ainsi très facile de gérer les erreurs par la suite en front (ici jquery) : 

```
$.ajax({
   ...
})
.success(function(data) {
    $("#theliagooglemap-success-msg").html(data.message).show()
})
.fail(function(jqXHR, textStatus, errorThrown){
    $("#loading-event").remove();
    $('#theliagooglemap-failed-body').html(jqXHR.responseJSON.message);
    $("#theliagooglemap-failed").modal("show");
});

````

**Comment by Soldras** [comment]
J'ai fait les changements nécessaire
Par contre je me suis basé sur le HookAnalytics pour la gestion de la configuration. Il faudra y jeter un oeil je pense.
