### ISSUE TITLE
[ConfigurationController] inutile d'utiliser le fullnamespace dans le code.

### ISSUE THREAD

**Issue by lunika** [Soldras/TheliaGoogleMap#4]
https://github.com/Soldras/TheliaGoogleMap/blob/master/Controller/ConfigurationController.php#L36

Il est inutile d'utiliser le fullnamespace, ça complique la lecture du code. Il faut l'importer dans le bloc des use au début du fichier

**Comment by Soldras** [comment]
Corrigé
